### ISSUE TITLE
You are amazing

### ISSUE THREAD

**Issue by davwheat** [shnupta/EnglishGCSE2017#1]
Of all the places to find these resources, GitHub was not where I expected.

Thank you.

**Comment by davwheat** [comment]
On a side note, could you please add a license so I know what I can and can't do with the info here?

(MIT will do :))

**Comment by shnupta** [comment]
Haha no worries. I've just added the license. Best of luck with your exams!

**Comment by davwheat** [comment]
Thank you so much!
